# Generated by Django 4.2.1 on 2023-05-21 17:17

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone
import uuid


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='TestModel',
            fields=[
                ('boolean', models.BooleanField(default=True, verbose_name='this is a boolean field')),
                ('char', models.CharField(help_text='added help text', max_length=220, unique=True, verbose_name='new Name')),
                ('date', models.DateField(default=django.utils.timezone.now)),
                ('decimal', models.DecimalField(decimal_places=2, max_digits=5)),
                ('email', models.EmailField(max_length=200)),
                ('file', models.FileField(blank=True, upload_to='uploads')),
                ('image', models.FileField(blank=True, upload_to='uploads')),
                ('integer', models.IntegerField()),
                ('positive_integer', models.PositiveIntegerField()),
                ('positive_small_int', models.PositiveSmallIntegerField()),
                ('slug', models.SlugField(blank=True)),
                ('text', models.TextField()),
                ('url', models.URLField()),
                ('uuid1', models.UUIDField(default=uuid.uuid4)),
                ('uuid2', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('updated', models.DateTimeField(auto_now=True)),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('date_and_time', models.DateTimeField()),
                ('choice', models.CharField(choices=[('one', 'number one'), ('two', 'number two'), ('three', 'number three'), ('four', 'number four')], max_length=10)),
                ('new_field2', models.CharField(blank=True, max_length=20)),
                ('user', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
