# Generated by Django 4.2.2 on 2023-06-12 07:32

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='EmailOTP',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('email', models.EmailField(max_length=255, unique=True)),
                ('otp', models.CharField(blank=True, max_length=7, null=True)),
                ('is_verified', models.BooleanField(default=False, help_text='if its true, that means user have verfied otp')),
                ('datetime', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name_plural': 'Email OTP',
            },
        ),
    ]
