# Generated by Django 4.2.2 on 2023-06-12 09:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('otp_app', '0002_phoneotp'),
    ]

    operations = [
        migrations.AlterField(
            model_name='phoneotp',
            name='phone',
            field=models.CharField(max_length=15, unique=True),
        ),
    ]
