# Generated by Django 4.2.2 on 2023-06-08 01:03

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('db_caching', '0001_initial'),
    ]

    operations = [
        migrations.DeleteModel(
            name='DbCaching',
        ),
    ]
